# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Quiz.create(question: 'At a party do you:', answer_a: 'interact with many, including strangers', answer_b: 'interact with a few, known to you')
Quiz.create(question: 'Are you more:', answer_a: 'realistic than speculative', answer_b: 'speculative than realistic')
Quiz.create(question: 'Is it worse to:', answer_a: 'have your head in the clouds', answer_b: 'be in a rut')
Quiz.create(question: 'Are you more impressed by:', answer_a: 'principles', answer_b: 'emotions')
Quiz.create(question: 'Are you more drawn toward the:', answer_a: 'convincing', answer_b: 'touching')
Quiz.create(question: 'Do you prefer to work:', answer_a: 'to deadlines', answer_b: 'just whenever')
Quiz.create(question: 'Do you tend to choose:', answer_a: 'rather carefully', answer_b: 'somewhat impulsively')
Quiz.create(question: 'At parties do you:', answer_a: 'stay late, with increasing energy', answer_b: 'leave early with decreased energy')
Quiz.create(question: 'Are you more attracted to:', answer_a: 'sensible people', answer_b: 'imaginative people')
Quiz.create(question: 'Are you more interested in:', answer_a: 'what is actual', answer_b: 'what is possible')
Quiz.create(question: 'In judging others are you more swayed by:', answer_a: 'laws than circumstances', answer_b: 'circumstances than laws')
Quiz.create(question: 'In approaching others is your inclination to be somewhat:', answer_a: 'objective', answer_b: 'personal')
Quiz.create(question: 'Are you more:', answer_a: 'punctual', answer_b: 'leisurely')
Quiz.create(question: 'Does it bother you more having things:', answer_a: 'incomplete', answer_b: 'completed')
Quiz.create(question: 'In your social groups do you:', answer_a: 'keep abreast of others\' happenings', answer_b: 'get behind on the news')
Quiz.create(question: 'In doing ordinary things are you more likely to:', answer_a: 'do it the usual way', answer_b: 'do it your own way')
Quiz.create(question: 'Writers should:', answer_a: 'say what they mean and mean what they say', answer_b: 'express things more by use of analogy')
Quiz.create(question: 'Which appeals to you more:', answer_a: 'consistency of thought', answer_b: 'harmonious human relationships')
Quiz.create(question: 'Are you more comfortable in making:', answer_a: 'logical judgments', answer_b: 'value judgments')
Quiz.create(question: 'Do you want things:', answer_a: 'settled and decided', answer_b: 'unsettled and undecided')
Quiz.create(question: 'Would you say you are more:', answer_a: 'serious and determined', answer_b: 'easy-going')
Quiz.create(question: 'In phoning do you:', answer_a: 'rarely question that it will all be said', answer_b: 'rehearse what you\'ll say')
Quiz.create(question: 'Facts:', answer_a: 'speak for themselves', answer_b: 'illustrate principles')
Quiz.create(question: 'Are visionaries:', answer_a: 'somewhat annoying', answer_b: 'rather fascinating')
Quiz.create(question: 'Are you more often:', answer_a: 'a cool-headed person', answer_b: 'a warm-hearted person')
Quiz.create(question: 'Is it worse to be:', answer_a: 'unjust', answer_b: 'merciless')
Quiz.create(question: 'Should one usually let events occur:', answer_a: 'by careful selection and choice', answer_b: 'randomly and by chance')
Quiz.create(question: 'Do you feel better about:', answer_a: 'having purchase', answer_b: 'having the option to buy')
Quiz.create(question: 'In company do you:', answer_a: 'initiate conversation', answer_b: 'wait to be approached')
Quiz.create(question: 'Common sense is:', answer_a: 'rarely questionable', answer_b: 'frequently questionable')
Quiz.create(question: 'Children often do not:', answer_a: 'make themselves useful enough', answer_b: 'exercise their fantasy enough')
Quiz.create(question: 'In making decisions do you feel more comfortable with:', answer_a: 'standards', answer_b: 'feelings')
Quiz.create(question: 'Are you more:', answer_a: 'firm than gentle', answer_b: 'gentle than firm')
Quiz.create(question: 'Which is more admirable:', answer_a: 'the ability to organize and be methodical', answer_b: 'the ability to adapt and make do')
Quiz.create(question: 'Do you put more value on:', answer_a: 'infinite', answer_b: 'open-minded')
Quiz.create(question: 'Does new and non-routine interaction with others:', answer_a: 'stimulate and energize you', answer_b: 'tax your reserves')
Quiz.create(question: 'Are you more frequently:', answer_a: 'a practical sort of person', answer_b: 'a fanciful sort of person')
Quiz.create(question: 'Are you more likely to:', answer_a: 'see how others are useful', answer_b: 'see how others see')
Quiz.create(question: 'Which is more satisfying:', answer_a: 'to discuss an issue thoroughly', answer_b: 'to arrive at agreement on an issue')
Quiz.create(question: 'Which rules you more:', answer_a: 'your head', answer_b: 'your heart')
Quiz.create(question: 'Are you more comfortable with work that is:', answer_a: 'contracted', answer_b: 'done on a casual basis')
Quiz.create(question: 'Do you tend to look for:', answer_a: 'the orderly', answer_b: 'whatever turns up')
Quiz.create(question: 'Do you prefer:', answer_a: 'many friends with brief contact', answer_b: 'a few friends with more lengthy contact')
Quiz.create(question: 'Do you go more by:', answer_a: 'facts', answer_b: 'principles')
Quiz.create(question: 'Are you more interested in:', answer_a: 'production and distribution', answer_b: 'design and research')
Quiz.create(question: 'Which is more of a compliment:', answer_a: 'There is a very logical person.', answer_b: 'There is a very sentimental person.')
Quiz.create(question: 'Do you value in yourself more that you are:', answer_a: 'unwavering', answer_b: 'devoted')
Quiz.create(question: 'Do you more often prefer the', answer_a: 'final and unalterable statement', answer_b: 'tentative and preliminary statement')
Quiz.create(question: 'Are you more comfortable:', answer_a: 'after a decision', answer_b: 'before a decision')
Quiz.create(question: 'Do you:', answer_a: 'speak easily and at length with strangers', answer_b: 'find little to say to strangers')
Quiz.create(question: 'Are you more likely to trust your:', answer_a: 'experience', answer_b: 'hunch')
Quiz.create(question: 'Do you feel:', answer_a: 'more practical than ingenious', answer_b: 'more ingenious than practical')
Quiz.create(question: 'Which person is more to be complimented - one of:', answer_a: 'clear reason', answer_b: 'strong feeling')
Quiz.create(question: 'Are you inclined more to be:', answer_a: 'fair-minded', answer_b: 'sympathetic')
Quiz.create(question: 'Is it preferable mostly to:', answer_a: 'make sure things are arranged', answer_b: 'just let things happen')
Quiz.create(question: 'In relationships should most things be:', answer_a: 're-negotiable', answer_b: 'random and circumstantial')
Quiz.create(question: 'When the doorbell rings do you:', answer_a: 'hasten to get to it first', answer_b: 'hope someone else will answer')
Quiz.create(question: 'Do you prize more in yourself:', answer_a: 'a strong sense of reality', answer_b: 'a vivid imagination')
Quiz.create(question: 'Are you drawn more to:', answer_a: 'fundamentals', answer_b: 'overtones')
Quiz.create(question: 'Which seems the greater error:', answer_a: 'to be too passionate', answer_b: 'to be too objective')
Quiz.create(question: 'Do you see yourself as basically:', answer_a: 'hard-headed', answer_b: 'soft-hearted')
Quiz.create(question: 'Which situation appeals to you more:', answer_a: 'the structured and scheduled', answer_b: 'the unstructured and unscheduled')
Quiz.create(question: 'Are you a person that is more:', answer_a: 'routinized than whimsical', answer_b: 'whimsical than routinized')
Quiz.create(question: 'Are you more inclined to be:', answer_a: 'easy to approach', answer_b: 'somewhat reserved')
Quiz.create(question: 'In writings do you prefer:', answer_a: 'the more literal', answer_b: 'the more figurative')
Quiz.create(question: 'Is it harder for you to:', answer_a: 'identify with others', answer_b: 'utilize others')
Quiz.create(question: 'Which do you wish more for yourself:', answer_a: 'clarity of reason', answer_b: 'strength of compassion')
Quiz.create(question: 'Which is the greater fault:', answer_a: 'being indiscriminate', answer_b: 'being critical')
Quiz.create(question: 'Do you prefer the:', answer_a: 'planned event', answer_b: 'unplanned event')
Quiz.create(question: 'Do you tend to be more:', answer_a: 'deliberate than spontaneous', answer_b: 'spontaneous than deliberate')
